### ISSUE TITLE
Django 3.0 访问 /admin 自动断开 server 的问题

### ISSUE THREAD

**Issue by dragon8github** [djangobook-cn/book-code#4]
P51 ~ P56 

一切正常，访问 localhost:8000 也正常。

访问 localhost:8000/admin ，输入账号密码，点击登陆，自动断开控制台的 server。

已使用『管理员权限运行 cmd』。

![image](https://user-images.githubusercontent.com/13919724/71761080-d5672180-2f01-11ea-83c0-78cc82ee08ad.png)

**Comment by dragon8github** [comment]
找了半天没办法，只能从 3.0 降级 2.2 版本。

pip install Django==2.2

**Comment by twz915** [comment]
@dragon8github 感谢反馈，这本书写的时候是使用 Django 2.x 来测试了的，当时Django 3.0 还没出来。
Django 3.0 最大的变化是支持了 ASGI，如果不使用这些，建议还是使用 Django 2.2 会比较稳定。
您反馈的问题我这边会尽快确认下能不能复现，如果你方便，最好能给一下能复现问题的最小化demo。
